### ISSUE TITLE
[Bug] <Local songs not appearing in Android 12 >

### ISSUE THREAD

**Issue by Tysina** [gokadzev/Musify#168]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/gokadzev/Musify/releases)**.
- [X] I will fill out all

### Current Behavior

When using the local song feature, no local songs are displayed.

### Expected Behavior

After granting the app storage permissions, Local Songs should show up.

### Steps To Reproduce

After giving the app all the permissions it requires, click more in the menus tand go to Local Songs  feature.

### Musify Version

V4.4.0

### Operating System Version

Android 12

### Additional information

By including the following, I hope I'm not asking for too much. Artist, folder, recently played, recently added, favorite tracks, and song name sorting from A-Z are the features i hope to see in the local song feature.And change the name Local Song to Local Music  

Thank you

**Comment by DarkCrypt** [comment]
@Tysina

Dev is working on another release. Try this debug app from comment [#127](https://github.com/gokadzev/Musify/issues/127#issuecomment-1429375535) for now, it should work. Worked for me on Android 13. I'd read a few more comments in that thread also.

**Comment by gokadzev** [comment]
> ###

Go to more > setup and check if your music folders are added. if they aren't added, add them otherwise wait for the next release.

About additional information: the app is mainly for online streaming, also since my pc specs isn't too good, it's harder to make changes in app. If i decide to release offline music player (which will be only for offline listening) then i may add these everything, but for now i can't promise.
