### ISSUE TITLE
Create your own playlist

### ISSUE THREAD

**Issue by marcossmtp** [gokadzev/Musify#254]
I think it could be a good improvement that would exist a section where you can create your personal playlist and can add songs.

**Comment by painkiller1717** [comment]
> I think it could be a good improvement that would exist a section where you can create your personal playlist and can add songs.

Yes I see this really important and would be useful!! Sometimes I want to put the music and let sound a playlist previously made, I usually use _Spotify Mod_ or _TubeMate_. But I would love can make playlists on this app, in songs or favorite songs, press on them and hold till a feature shows up to **add to the current playlist** and **add to queue**. Or another playlist which you want create. Would be a great improvement to Musify!! 🙏🙏

**Comment by gokadzev** [comment]
Is it about offline music playlist or online one?

**Comment by painkiller1717** [comment]
> Is it about offline music playlist or online one?

Online music, placing them on favorites or hold on the song and possibility of add to some playlist or to queue.

**Comment by gokadzev** [comment]
> > Is it about offline music playlist or online one?
> 
> Online music, placing them on favorites or hold on the song and possibility of add to some playlist or to queue.

About favorites, you can like song and it will be appeared in the "Liked songs" playlist. btw you also can add your own personal youtube playlists in Musify using "User playlists" page.

**Comment by marcossmtp** [comment]
> > > Is it about offline music playlist or online one?
> > 
> > 
> > Online music, placing them on favorites or hold on the song and possibility of add to some playlist or to queue.
> 
> About favorites, you can like song and it will be appeared in the "Liked songs" playlist. you also can add your own personal youtube playlists in Musify using "User playlists" page.

Yes, of course, but it's not the same can reproduce all your favourites, you can have thousands. And can create playlists separated with them it would be nice.
And I see the youtube option add playlist and is nice, but I dont use youtube for music (I know musify takes the music from there) and create a playlist in youtube and them export to musify is double work.
I think musify is a great app that have the option of create his own playlist is a good improvement indepent of the rest of the options, at least for me.
Thanks

**Comment by painkiller1717** [comment]
> > > Is it about offline music playlist or online one?
> > 
> > Online music, placing them on favorites or hold on the song and possibility of add to some playlist or to queue.
> 
> About favorites, you can like song and it will be appeared in the "Liked songs" playlist. you also can add your own personal youtube playlists in Musify using "User playlists" page.

Same as marcosstmp said previously, agree with all.

**Comment by painkiller1717** [comment]
What happened with this feature? Something like can create my own playlist of the favorite songs I chose, and also add to queue. This is apart of be possible of add Youtube playlist, which is a great feature too, but I mean can make my own playlists of favorite songs, and having the feature of add to queue.

Regards and thank you for this awesome project! 🙌🙌🙏 I already donated you money because you deserve it.

**Comment by gokadzev** [comment]
> What happened with this feature? Something like can create my own playlist of the favorite songs I chose, and also add to queue. This is apart of be possible of add Youtube playlist, which is a great feature too, but I mean can make my own playlists of favorite songs, and having the feature of add to queue.
> 
> Regards and thank you for this awesome project! raised_handsraised_handspray I already donated you money because you deserve it.

It's not as easy as it seems. Having online and offline playing support at the same time has its own drawbacks because they work with the same code but have different structures. Additionally, I'm the only active contributor who develops the app. Unfortunately, at the moment, I can only suggest a "favorites" list and exporting playlists from YouTube.

I prefer focusing on the app's stability and adding new features, rather than implementing alternatives to existing features that may have negative effects. Adding above listed features could lead to various issues that I'd like to avoid.
