### ISSUE TITLE
Musify on OpenAPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [gokadzev/Musify#386]
Hey Valeri,

I'm running a open source repo for Android apps at https://www.openapk.net and I would like to have Musify listed in the repo. Please review the listing at https://www.openapk.net/musify/com.gokadzev.musify/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by gokadzev** [comment]
> Hey Valeri,
> 
> I'm running a open source repo for Android apps at https://www.openapk.net and I would like to have Musify listed in the repo. Please review the listing at https://www.openapk.net/musify/com.gokadzev.musify/
> 
> It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !


Hello,

Yes, it's absolutely okay as it includes everything from the GitHub repository link to the author's information. However, as I'm looking at it, it seems to have missed several updates and shows the number of stars inaccurately. Just to keep you informed.

**Comment by mobilenetworkltd** [comment]
Hello,

thank you for pointing this to me. It is important to be as accurate as possible since I want my users to be aware of the developers info and to be able to send you a donation also. The app is updated now. Now I am working on a tool to autoupdate them when a new version is available. Please feel free to message me if you notice something else I can improve.

**Comment by gokadzev** [comment]
> Hello,
> 
> thank you for pointing this to me. It is important to be as accurate as possible since I want my users to be aware of the developers info and to be able to send you a donation also. The app is updated now. Now I am working on a tool to autoupdate them when a new version is available. Please feel free to message me if you notice something else I can improve.

You're welcome. After fast-check:

- Any attempt to download ends with the message "ERROR - PAGE NOT FOUND."

- Is it really necessary to mirror APK files? Since you add open-source apps there, I think the original download links would be much better. Plus, it would be less of a headache for the auto-updater, as getting all versions using the GitHub API is much easier than mirroring all of them and adding them there.

- If the app has several variants, it shows "Download()" without a size. You could either remove the parentheses in that case or just put the universal APK size.

**Comment by mobilenetworkltd** [comment]
Thank you for the feedback. I will take a closer look at what you have recommended. Can you be more exact in which conditions you get the download error message. What browser are you using and what OS, since when I am testing everything works.

**Comment by westnordost** [comment]
Just linking to GitHub (or other forges, depending on where it is hosted) sounds like an _excellent_ idea, because
- **more secure** from a user-perspective: users don't need to trust that the apk has not been tempered with. That would be a unique selling point over APKMirror, but even F-Droid (i.e. you must trust F-Droid people to not tamper with it)
- **more secure** from an architecture perspective: by not hosting these yourself, you pretty much remove yourself from being a juicy target of being hacked by malicious actors that want to inject (all hosted) distribution with their own code.
- **more control by app authors**: sometimes app authors want/need to pull certain versions of their app from distribution because of critical bugs or security issues. They can remove releases in GitHub. If you don't host the releases yourself, it would automatically also work for OpenAPK
- as far as I can tell, not less stable: Redundancy in hosting the APK is not really necessary, as if for some reason the repository (or Github as a whole) vanishes, there is probably a good reason for it and/or the scripts that pull the releases from GitHub would fail on your side anyway
