### ISSUE TITLE
[Bug] <The Spanish language disappeared>

### ISSUE THREAD

**Issue by cryfhan** [gokadzev/Musify#435]
### Acknowledgements

- [X] I have searched the existing issues and confirmed that this is a new issue, not a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version. You can find the latest version [here](https://github.com/gokadzev/Musify/releases).
- [X] I will fill out all the sections in this issue report.

### Current Behavior

When entering the application options, the Spanish language does not appear in the language menu

### Expected Behavior

When you enter settings and select the language option, the Spanish language appears to be selected

### Steps To Reproduce

1. Entry to settings.
2. In preferences I select language
3. When you scroll through the menu, Spanish does not appear.

### Musify Version

8.7.1

### Device And Operating System

Honor magic 6 pro (android 14)

### Android Version You Use

Android 14

### Additional Information

Since update 8.7 the Spanish language disappeared.

**Comment by gokadzev** [comment]
@cryfhan Hi, this isn’t a bug. The Spanish language was removed in this commit (https://github.com/gokadzev/Musify/commit/2231514760598f47a57fe2e926379482ccd120e3) because it doesn't have a translator. If anyone decides to take on the translation, I’ll add them to the official translators list, along with the Spanish language.

**Comment by gokadzev** [comment]
Okay, I'll add back Spanish language again
