### ISSUE TITLE
Automatic Playing. 

### ISSUE THREAD

**Issue by glorymaster** [gokadzev/Musify#73]
### Describe your suggested feature

after playing a searched song or any song nothings come after it, just that it? the player will automatically stop? I suggest that it will automatically play any song related to the song I just played. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by gokadzev** [comment]
@glorymaster "play automatically next song" feature is already implemented, since it's in BETA state and needs improvement it's disabled by default. to enable it click arrow above star (right side)

<img width="32%" src="https://raw.githubusercontent.com/gokadzev/Musify/master/fastlane/metadata/android/en-US/images/phoneScreenshots/03.jpg" align="center" alt="screenshot" />
