### ISSUE TITLE
Album artwork (and other missing metadata) support for downloads

### ISSUE THREAD

**Issue by ArtikusHG** [gokadzev/Musify#83]
### Describe your suggested feature

It would be nice if the app could also write metadata into the downloaded song. Some downloaders grab metadata from Spotify, but even something as simple as setting the video thumbnail as the album artwork would be really good.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by gokadzev** [comment]
> ### Describe your suggested feature
> It would be nice if the app could also write metadata into the downloaded song. Some downloaders grab metadata from Spotify, but even something as simple as setting the video thumbnail as the album artwork would be really good.
> 
> ### Other details
> _No response_
> 
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> * [x]  I have written a short but informative title.
> * [x]  I will fill out all of the requested information in this form.

Here is the problem, since we use youtube as provider service, it gives as audio with m4a format originally and there's not any flutter plugin which can edit m4a meta tags. We just change its extension to mp3/flac, that's why available plugins gives me error that it's not mp3. It needs to be converted with ffmpeg or something, but another problem: ffmpeg needs api version 24 (Android 7.0) and it will slow down the download process. Currently I prefer to remain everything the same, as it is.
